// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkeWcUkqNcshfWDJ4cnFXvqH5nKjht1zQ',
    appId: '1:593963113029:web:13dc9df49089ca0c40612c',
    messagingSenderId: '593963113029',
    projectId: 'ideaflow-8e13e',
    authDomain: 'ideaflow-8e13e.firebaseapp.com',
    storageBucket: 'ideaflow-8e13e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfgJjOeYh8TPdgD1LMybbO9qHEqZVT3UM',
    appId: '1:593963113029:android:d670d03faa5253b440612c',
    messagingSenderId: '593963113029',
    projectId: 'ideaflow-8e13e',
    storageBucket: 'ideaflow-8e13e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsPhS_uxRy6yY55hz1bGY_B7k4MthUjjY',
    appId: '1:593963113029:ios:732e633f15e6f2e840612c',
    messagingSenderId: '593963113029',
    projectId: 'ideaflow-8e13e',
    storageBucket: 'ideaflow-8e13e.firebasestorage.app',
    iosBundleId: 'com.example.ideaflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsPhS_uxRy6yY55hz1bGY_B7k4MthUjjY',
    appId: '1:593963113029:ios:732e633f15e6f2e840612c',
    messagingSenderId: '593963113029',
    projectId: 'ideaflow-8e13e',
    storageBucket: 'ideaflow-8e13e.firebasestorage.app',
    iosBundleId: 'com.example.ideaflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkeWcUkqNcshfWDJ4cnFXvqH5nKjht1zQ',
    appId: '1:593963113029:web:5c266b22e7eb135240612c',
    messagingSenderId: '593963113029',
    projectId: 'ideaflow-8e13e',
    authDomain: 'ideaflow-8e13e.firebaseapp.com',
    storageBucket: 'ideaflow-8e13e.firebasestorage.app',
  );
}
